server:
   port: 8094

dbValues: "{connectionString: 'http://__', userName: 'foo', password: 'pass'}"

my:
   #it will be overridden by whatever is in the config server
   greeting: smth
   list:
      values: One,Two,Three

db:
   connection: "{connectionString: 'http://__', userName: 'foo', password: 'pass'}"
   host: 127.0.0.1
   port: 1200

#get all endpoints. Expose everything
management.endpoints.web.exposure.include: "*"

#spring.profiles.active: test

#url where the config server is running. The application is gonna connect to the spring
#cloud config server using this URL and it's gonna pull up all properties
sping.cloud.config.uri: http://localhost:8888/
